from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from uuid import uuid4

import config
from models import db
from models.generated_file import GeneratedFile
from models.interview import Interview
from models.project import Project
from services.generated_file_ownership import stored_path_project_id
from services.managed_write_commit_guard import open_managed_write_commit_guard
from services.storage_paths import (
    ManagedWriteFile,
    ensure_managed_id_dir,
    open_managed_file_for_create,
    resolve_managed_path,
)


_INVALID_FILENAME_RE = re.compile(r'[<>:"/\\|?*\x00-\x1f]')
_WINDOWS_RESERVED_STEMS = {
    "CON", "PRN", "AUX", "NUL",
    *(f"COM{i}" for i in range(1, 10)),
    *(f"LPT{i}" for i in range(1, 10)),
}


@dataclass
class OutputTarget:
    filename: str
    full_path: str
    stored_path: str
    written_stat: os.stat_result | None = None


@dataclass
class OutputWriteFile:
    """Managed writer that records the exact final file generation on close."""

    managed: ManagedWriteFile
    target: OutputTarget
    _closed: bool = False

    @property
    def stream(self):
        return self.managed.stream

    @property
    def stat_result(self):
        return self.managed.stat_result

    def close(self) -> None:
        if self._closed:
            return
        try:
            if not self.managed.stream.closed:
                self.managed.stream.flush()
                self.target.written_stat = os.fstat(self.managed.stream.fileno())
        finally:
            self.managed.close()
            self._closed = True

    def __enter__(self) -> "OutputWriteFile":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()


def _output_root() -> Path:
    return Path(config.OUTPUT_DIR).resolve()


def safe_output_filename(filename: str) -> str:
    """Return a single cross-platform filename while preserving Japanese text."""
    value = str(filename or "").strip()
    value = _INVALID_FILENAME_RE.sub("_", value)
    value = value.strip(" .")
    if not value or value in {".", ".."}:
        raise ValueError("output filename is empty or invalid")

    stem = value.split(".", 1)[0].upper()
    if stem in _WINDOWS_RESERVED_STEMS:
        value = f"_{value}"
    return value


def _resolve_stored_path(stored_path: str) -> Path:
    """Resolve one DB stored_path and reject linked paths/out-of-root targets."""
    return resolve_managed_path(config.OUTPUT_DIR, stored_path)


def _unique_storage_name(filename: str) -> str:
    """Return a short internal storage name independent of the download filename."""
    suffix = Path(filename).suffix
    return f"{uuid4().hex}{suffix}"


def _file_generation(info: os.stat_result) -> tuple[int, int, int, int, int, int]:
    return (
        int(info.st_dev), int(info.st_ino), int(info.st_mode),
        int(info.st_size), int(info.st_mtime_ns), int(info.st_ctime_ns),
    )


def _generation_params_with_artifact_sha256(
    generation_params_json: str | None,
    artifact_sha256: str,
) -> str:
    """Merge the registrar-proven byte hash into existing generation metadata."""
    params = {}
    if generation_params_json:
        try:
            params = json.loads(generation_params_json)
        except (json.JSONDecodeError, TypeError) as exc:
            raise ValueError("generated-file generation_params_json is invalid") from exc
        if not isinstance(params, dict):
            raise ValueError("generated-file generation_params_json must be a JSON object")

    digest = str(artifact_sha256 or "").strip().lower()
    if len(digest) != 64 or any(ch not in "0123456789abcdef" for ch in digest):
        raise ValueError("generated-file artifact SHA-256 is invalid")

    existing = str(params.get("artifact_sha256") or "").strip().lower()
    if existing and existing != digest:
        raise ValueError("generated-file artifact SHA-256 disagrees with generated bytes")
    params["artifact_sha256"] = digest
    return json.dumps(params, ensure_ascii=False, sort_keys=True)


def generated_file_expected_sha256(gf: GeneratedFile) -> str | None:
    """Return a registered byte hash when present; legacy rows remain readable."""
    raw = gf.generation_params_json
    if not raw:
        return None
    try:
        params = json.loads(raw)
    except (json.JSONDecodeError, TypeError) as exc:
        raise ValueError("generated-file generation metadata is invalid") from exc
    if not isinstance(params, dict):
        raise ValueError("generated-file generation metadata is invalid")

    value = params.get("artifact_sha256")
    if value in {None, ""}:
        return None
    digest = str(value).strip().lower()
    if len(digest) != 64 or any(ch not in "0123456789abcdef" for ch in digest):
        raise ValueError("generated-file artifact SHA-256 metadata is invalid")
    return digest


def _validate_generated_file_ownership(
    target: OutputTarget,
    *,
    project_id: int,
    interview_id: int | None,
) -> tuple[int, int | None]:
    """Bind DB ownership metadata to the exact project-scoped output namespace."""
    project_id = int(project_id)
    if project_id <= 0:
        raise ValueError("generated-file project_id must be positive")
    if db.session.get(Project, project_id) is None:
        raise ValueError("generated-file project does not exist")

    path_project_id = stored_path_project_id(target.stored_path)
    if path_project_id != project_id:
        raise ValueError(
            "generated output stored_path project namespace does not match project_id"
        )

    normalized_interview_id = None
    if interview_id is not None:
        normalized_interview_id = int(interview_id)
        if normalized_interview_id <= 0:
            raise ValueError("generated-file interview_id must be positive")
        interview = db.session.get(Interview, normalized_interview_id)
        if interview is None:
            raise ValueError("generated-file interview does not exist")
        if int(interview.project_id) != project_id:
            raise ValueError("generated-file interview belongs to another project")

    return project_id, normalized_interview_id


def _discard_output_target_if_same_generation(target: OutputTarget) -> None:
    """Best-effort cleanup through a re-pinned exact-generation guard."""
    expected = target.written_stat
    if expected is None:
        return
    guard = None
    try:
        guard = open_managed_write_commit_guard(
            config.OUTPUT_DIR,
            target.stored_path,
            expected,
        )
        guard.discard()
    except (OSError, ValueError):
        # If the public namespace no longer names the written generation, leave
        # both the successor and any unreachable predecessor untouched rather than
        # risk deleting the wrong file.
        pass
    finally:
        if guard is not None:
            guard.close()


def prepare_output_target(project_id: int, filename: str) -> OutputTarget:
    """Create a safe project-scoped, collision-resistant generated-file target.

    ``filename`` remains the user-facing download name. The filesystem/DB
    ``stored_path`` uses a UUID-only internal basename plus the original extension,
    so concurrent generations cannot collide and long display names cannot push the
    filesystem component beyond common 255-byte limits. The project ID directory
    must be a normal directory, never a symlink or Windows junction/reparse point.
    """
    project_id = int(project_id)
    if project_id <= 0:
        raise ValueError("project_id must be positive")

    safe_name = safe_output_filename(filename)
    storage_name = _unique_storage_name(safe_name)
    ensure_managed_id_dir(config.OUTPUT_DIR, project_id)
    stored_path = f"{project_id}/{storage_name}"
    full_path = _resolve_stored_path(stored_path)
    return OutputTarget(
        filename=safe_name,
        full_path=str(full_path),
        stored_path=stored_path,
    )


def open_output_target_for_write(target: OutputTarget) -> OutputWriteFile:
    """Exclusively create one prepared output through the pinned write boundary."""
    managed_path = _resolve_stored_path(target.stored_path)
    if managed_path != Path(target.full_path).resolve():
        raise ValueError("output target path mismatch")
    managed = open_managed_file_for_create(config.OUTPUT_DIR, target.stored_path)
    return OutputWriteFile(managed=managed, target=target)


def _compensate_committed_generated_file(gf: GeneratedFile, cause: Exception) -> None:
    """Remove a just-committed row when post-commit namespace verification fails."""
    try:
        db.session.delete(gf)
        db.session.commit()
    except Exception as cleanup_exc:
        db.session.rollback()
        raise RuntimeError(
            "generated output namespace changed during DB commit and compensating row deletion failed"
        ) from cleanup_exc


def register_generated_file(
    target: OutputTarget,
    *,
    project_id: int,
    file_type: str,
    file_format: str,
    interview_id: int | None = None,
    generation_params_json: str | None = None,
) -> GeneratedFile:
    """Register only the exact file generation produced by the managed writer.

    A second guard is acquired after the report library closes its writer. That
    guard re-pins the current exact file generation and its ancestor chain, stays
    live through DB commit, and verifies the public managed pathname again after
    commit. Newly registered ordinary artifacts receive a SHA-256 of that exact
    pinned generation so later downloads can reject in-place byte tampering.
    Formal artifacts retain their stricter exporter-owned metadata contract; when
    formal metadata is supplied, its hash is rechecked against the same pinned
    bytes here. Project/interview ownership is validated against the target's
    project-scoped storage namespace before the row can be committed. Registration
    also requires a clean SQLAlchemy session so its internal commit cannot publish
    unrelated caller mutations. Rollback cleanup is performed through the pinned
    guard rather than check-then-unlink on the mutable pathname.
    """
    expected = target.written_stat
    if expected is None:
        raise ValueError("generated output writer did not record final file identity")

    guard = None
    gf = None
    committed = False
    try:
        if db.session.new or db.session.dirty or db.session.deleted:
            raise RuntimeError("generated-file registration requires a clean database session")

        normalized_project_id, normalized_interview_id = _validate_generated_file_ownership(
            target,
            project_id=project_id,
            interview_id=interview_id,
        )

        guard = open_managed_write_commit_guard(
            config.OUTPUT_DIR,
            target.stored_path,
            expected,
        )
        guard.verify_namespace()

        artifact_sha256 = guard.sha256()
        if file_type != "approved_analysis" or generation_params_json:
            generation_params_json = _generation_params_with_artifact_sha256(
                generation_params_json,
                artifact_sha256,
            )
        guard.verify_namespace()

        gf = GeneratedFile(
            project_id=normalized_project_id,
            interview_id=normalized_interview_id,
            file_type=file_type,
            file_format=file_format,
            original_filename=target.filename,
            stored_path=target.stored_path,
            generation_params_json=generation_params_json,
        )
        db.session.add(gf)
        db.session.commit()
        committed = True

        try:
            guard.verify_namespace()
        except Exception as namespace_exc:
            _compensate_committed_generated_file(gf, namespace_exc)
            try:
                guard.discard()
            except (OSError, ValueError):
                pass
            raise namespace_exc
        return gf
    except Exception:
        if not committed:
            db.session.rollback()
            if guard is not None:
                try:
                    guard.discard()
                except (OSError, ValueError):
                    pass
            else:
                _discard_output_target_if_same_generation(target)
        raise
    finally:
        if guard is not None:
            guard.close()


def get_full_path(gf: GeneratedFile) -> str:
    return str(_resolve_stored_path(gf.stored_path))


def file_exists(gf: GeneratedFile) -> bool:
    try:
        return Path(get_full_path(gf)).is_file()
    except ValueError:
        return False
